Ecommerce/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Ecommerce.Common.Core;
using Ecommerce.Common.Models;
using Ecommerce.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Ecommerce.Controllers
{
    public class ProductsController : Controller
    {
        private IUnitOfWork _uof;

        public ProductsController(IUnitOfWork uof)
        {
            _uof = uof;
        }

        // GET: Product
        public ActionResult Index(int page)
        {
            var products = _uof.ProductRepository.GetWithPagination(page);
            var pagedProducts = new StaticPagedList<Product>(products.Items, products.PageNumber, products.PageSize, products.TotalItemCount);
            return View(pagedProducts);
        }


        // GET: v/Details/5
        public ActionResult Details(int id)
        {
            Expression<Func<Product, object>>[] includeFunction = { (x => x.ProductModel), (x => x.ProductReview) };
            var product = _uof.ProductRepository.IncludeMultiple(includeFunction, (x => x.ProductId == id)).SingleOrDefault();
            return View(product);
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, IFormCollection collection)
        {
            try
            {
                var product = new Product()
                {
                    Name = collection["Name"],
                    ProductNumber = "AA-" + Guid.NewGuid().ToString().Substring(0, 3),
                    SafetyStockLevel = Convert.ToInt16(collection["SafetyStockLevel"]),
                    Color = collection["Color"],
                    StandardCost = Convert.ToDecimal(collection["StandardCost"]),
                    ListPrice = Convert.ToDecimal(collection["ListPrice"]),
                    DaysToManufacture = Convert.ToInt32(collection["DaysToManufacture"]),
                    SellStartDate = Convert.ToDateTime(collection["SellStartDate"]),
                    SellEndDate = Convert.ToDateTime(collection["SellEndDate"]),
                    ModifiedDate = DateTime.Now,
                    ReorderPoint = 1

                };
                _uof.ProductRepository.Insert(product);
                _uof.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _uof.Rollback();
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _uof.ProductRepository.GetByID(id);
            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var product = _uof.ProductRepository.GetByID(id);

                product.Name = collection["Name"];
                //ProductNumber = Guid.NewGuid().ToString().Substring(0, 3),  just for create
                product.SafetyStockLevel = Convert.ToInt16(collection["SafetyStockLevel"]);
                product.Color = collection["Color"];
                product.StandardCost = Convert.ToDecimal(collection["StandardCost"]);
                product.ListPrice = Convert.ToDecimal(collection["ListPrice"]);
                product.DaysToManufacture = Convert.ToInt32(collection["DaysToManufacture"]);
                product.SellStartDate = Convert.ToDateTime(collection["SellStartDate"]);
                product.SellEndDate = Convert.ToDateTime(collection["SellEndDate"]);
                product.ModifiedDate = DateTime.Now;
                product.ReorderPoint = 1;

                _uof.ProductRepository.Update(product);
                _uof.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {


            var product = _uof.ProductRepository.GetByID(id);
            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                //CASCADE PROBLEM WİTH MULTI TABLE NOT JUST REVIEWS
                //var reviewsOfProduct = _uof.ProductReviewRepository.Get(x => x.ProductId == id);
                //foreach (var review in reviewsOfProduct)
                //{
                //    _uof.ProductReviewRepository.Delete(review.ProductReviewId);
                //}
                var product = _uof.ProductRepository.GetByID(id);
                _uof.ProductRepository.Delete(product);
                _uof.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _uof.Rollback();
                return View();
            }
        }
    }
}

Ecommerce/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Common.Core;
using Ecommerce.Common.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace Ecommerce.Controllers
{
    public class ReviewsController : Controller
    {

        private IUnitOfWork _uof;


        public ReviewsController(IUnitOfWork uof)
        {
            _uof = uof;
        }

        // GET: Reviews
        public ActionResult Index(int page)
        {
            try
            {
                var reviews = _uof.ProductReviewRepository.GetWithPagination(page);
                var pagedList = new StaticPagedList<ProductReview>(reviews.Items, reviews.PageNumber, reviews.PageSize, reviews.TotalItemCount);
                return View(pagedList);
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var review = _uof.ProductReviewRepository.GetByID(id);
                return View(review);
            }
            catch (Exception )
            {
                return View();
            }
        }
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        public ActionResult Edit(int id)
        {
            var review = _uof.ProductReviewRepository.GetByID(id);
            return View(review);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                var review = _uof.ProductReviewRepository.GetByID(id);
                review.Comments = collection["comments"];
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: Reviews/Delete/5
        public ActionResult Delete(int id)
        {
            var review = _uof.ProductReviewRepository.GetByID(id);
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {

                _uof.ProductReviewRepository.Delete(id);
                _uof.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Ecommerce/Views/Shared/_FieldLayout.cshtml
<div class="efield">
    @*<div class="elabel">
        @Html.Label("", null, new {@for = Html.ViewContext.HttpContext.Items[Settings.ContextKey] + ViewData.TemplateInfo.GetFullHtmlFieldName(string.Empty) + ViewData["__idpostfix"]})
    </div>*@
    <div class="einput">
        @RenderBody()
    </div>
    @Html.ValidationMessage("")
</div>

Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <environment include="Development">

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">*@

        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>

    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/js/mvc-grid/mvc-grid.js"></script>




</head>
<body>
    @*<script>
        [].forEach.call(document.getElementsByClassName('mvc-grid'), function (element) {
            new MvcGrid(element);
        });
    </script>*@

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reviews" asp-action="Index">Review</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()



        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Ecommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="@Url.Content("~/js/AwesomeMvc.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/awem.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/utils.js")" type="text/javascript"></script>

    @Html.AntiForgeryToken()


    <environment include="Development">

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>